### ISSUE TITLE
require is not a function error when upgrading to TailwindCSS v1+

### ISSUE THREAD

**Issue by CaitlinWeb** [dobromir-hristov/tailwindcss-export-config#7]
I'm getting an error with tailwind-export-config version 2.0.0-beta.1 and TailwindCSS version 1.0.2.

The command I'm running (with filepaths removed) is `tailwindcss-export-config --config=<config file> --destination=<output folder> --format=scss`

Here is the error I get (filepath removed):

``` 
require(...) is not a function

<filepath>node_modules\tailwindcss-export-config\cli.js:62
  throw e
  ^

TypeError: require(...) is not a function
    at Object.<anonymous> (<filepath>tailwind.js:27:57)
    at Module._compile (internal/modules/cjs/loader.js:723:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:734:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:659:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at resolveConfig (<filepath>node_modules\tailwindcss-export-config\dist\index.js:31:14)
    at new ConvertTo (<filepath>node_modules\tailwindcss-export-config\dist\index.js:348:20)```

**Comment by CaitlinWeb** [comment]
@dobromir-hristov also want to add that I tried tailwind-export-config version 2.0.0-beta.1 with TailwindCSS versions 1.0.0-beta.1, 1.0.0-beta.4, and 1.0.0-beta.10 also and had the same result.

tailwind-export-config version 1.0.4 with TailwindCSS version 0.7.4 works as expected.

**Comment by dobromir-hristov** [comment]
Hey, could you show me your config,

**Comment by CaitlinWeb** [comment]
🤦‍♀ 

My mistake, I didn't realize I needed to update my config file when updating TailwindCSS to the new version. Thanks to your request, @dobromir-hristov, I did that and it worked fine 😄 

So if anyone else runs into this issue like me, make sure your config file is correct.
